BIMA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

from BIMA.views import dashboard

urlpatterns = [

    path('accounts/', include('allauth.urls')),

    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', RedirectView.as_view(url='/login', permanent=False)),    
    path('dashboard', login_required(dashboard), name='dashboard'),
    path('dashboard/', include('informasi.urls')),
    path('', include('mahasiswa.urls')),
    path('', include('dosen.urls')),
    path('dashboard/master-data/', include('masterData.urls')),
    path('dashboard/', include('ormawa.urls')),
    path('dashboard/', include('proposalLPJ.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ormawa/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

# Kepengurusan
urlpatterns = [
    path("kepengurusan", login_required(views.KepengurusanView.index), name="kepengurusan.index"),
    path("kepengurusan/show/<str:ormawaName>/<int:periodeID>", login_required(views.KepengurusanView.show), name="kepengurusan.show"),
    path("kepengurusan/create", login_required(views.KepengurusanView.create), name="kepengurusan.create"),
    path("kepengurusan/edit/<int:kepengurusanID>", login_required(views.KepengurusanView.edit), name="kepengurusan.edit"),
    path("kepengurusan/delete<int:kepengurusanID>", login_required(views.KepengurusanView.delete), name="kepengurusan.delete"),
]

urlpatterns += [
    path("profile-ormawa", login_required(views.ProfileOrmawaView.index), name="profileOrmawa.index"),
    path("profile-ormawa/edit", login_required(views.ProfileOrmawaView.edit), name="profileOrmawa.edit"),
]
    
# Pengurus
urlpatterns += [
    path("pengurus", login_required(views.PengurusView.index), name="pengurus.index"),
    path("pengurus/create/<int:kepengurusanID>", login_required(views.PengurusView.create), name="pengurus.create"),
    path("pengurus/edit/<int:pengurusID>", login_required(views.PengurusView.edit), name="pengurus.edit"),
    path("pengurus/delete/<int:pengurusID>", login_required(views.PengurusView.delete), name="pengurus.delete"),
]

# Struktur Organisasi
urlpatterns += [
    path("struktur-organisasi", login_required(views.StrukturOrgView.index), name="strukturorg.index"),
    path("struktur-organisasi/create/<int:ormawaID>", login_required(views.StrukturOrgView.create), name="strukturorg.create"),
    path("struktur-organisasi/edit/<int:strukturOrgID>", login_required(views.StrukturOrgView.edit), name="strukturorg.edit"),
    path("struktur-organisasi/delete/<int:strukturOrgID>", login_required(views.StrukturOrgView.delete), name="strukturorg.delete"),
]

# RKT
urlpatterns += [
    path("kegiatan/rkt", login_required(views.RKTView.index), name="kegiatan.index"),
    path("kegiatan/rkt/create", login_required(views.RKTView.create), name="kegiatan.create"),
    path("kegiatan/rkt/edit/<int:kegiatanID>", login_required(views.RKTView.edit), name="kegiatan.edit"),
    path("kegiatan/rkt/delete/<int:kegiatanID>", login_required(views.RKTView.delete), name="kegiatan.delete"),
    path("kegiatan/rkt/verify/<int:kegiatanID>", login_required(views.RKTView.admin_verify), name="kegiatan.verify"),
]

# Duta Kampus
urlpatterns += [
    path("kegiatan/duta-kampus", login_required(views.DutaKampusView.index), name="dutaKampus.index"),
    path("kegiatan/duta-kampus/create", login_required(views.DutaKampusView.create), name="dutaKampus.create"),
    path("kegiatan/duta-kampus/edit/<int:dutaKampusID>", login_required(views.DutaKampusView.edit), name="dutaKampus.edit"),
    path("kegiatan/duta-kampus/delete/<int:dutaKampusID>", login_required(views.DutaKampusView.delete), name="dutaKampus.delete"),
]

ormawa/models.py
from django.db import models
from dosen.models import Dosen
from mahasiswa.models import Mahasiswa
from masterData.models import Ormawa, Periode, Level

class StrukturOrg(models.Model):
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=100)
    ormawa = models.ForeignKey(Ormawa, on_delete=models.CASCADE)
    active = models.BooleanField()
    
    class Meta:
        verbose_name_plural = "Struktur Organisasi"

    def __str__(self):
        return f'{self.nama}'
    
class Kepengurusan(models.Model):
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=100)
    ormawa = models.ForeignKey(Ormawa, related_name='kepengurusan_ormawa', on_delete=models.CASCADE)
    periode = models.ForeignKey(Periode, on_delete=models.CASCADE)
    ketua = models.ForeignKey(Mahasiswa, related_name='kepengurusan_ketua', on_delete=models.CASCADE)
    sekretaris = models.ForeignKey(Mahasiswa, related_name='kepengurusan_sekretaris', on_delete=models.CASCADE)
    npp_wr = models.ForeignKey(Dosen, related_name='kepengurusan_wr', on_delete=models.CASCADE)
    npp_pembina = models.ForeignKey(Dosen, related_name='kepengurusan_pembina', on_delete=models.CASCADE)
    or_koord = models.ForeignKey(Mahasiswa, related_name='kepengurusan_or_koord', on_delete=models.CASCADE)
    jabatan_koord = models.CharField(max_length=40)
    
    class Meta:
        verbose_name_plural = "Kepengurusan"
    
    def __str__(self):
        return f'{self.nama} - {self.ormawa} - {self.periode}'

class Pengurus(models.Model):
    id = models.AutoField(primary_key=True)
    mahasiswa = models.ForeignKey(Mahasiswa, on_delete=models.CASCADE)
    struktur = models.ForeignKey(StrukturOrg, on_delete=models.CASCADE)
    
    kepengurusan = models.ForeignKey(Kepengurusan, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = "Pengurus"

class StatusKegiatan(models.TextChoices):
    USULAN = 'Usulan'
    USULAN_VALID = 'Usulan Valid'
    PROPOSAL = 'Proposal'
    PROPOSAL_VALID = 'Proposal Valid'
    LPJ = 'LPJ'
    LPJ_VALID = 'LPJ Valid'
    REJECTED = 'Rejected'


class JenisKegiatan(models.Model):
    id = models.AutoField(primary_key=True)
    nama_jenis = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Jenis Kegiatan"

    def __str__(self):
        return self.nama_jenis

class Kegiatan(models.Model):
    id = models.AutoField(primary_key=True)
    nomor = models.CharField(max_length=100)
    nama = models.CharField(max_length=100)
    tema = models.CharField(max_length=200)
    tgl_mulai = models.DateField()
    tgl_selesai = models.DateField()
    mhs_pj = models.ForeignKey(Mahasiswa, related_name='kegiatan_pj', on_delete=models.CASCADE)
    mhs_koord = models.ForeignKey(Mahasiswa, related_name='kegiatan_koord', on_delete=models.CASCADE)
    tempat = models.CharField(max_length=200)
    max_peserta = models.IntegerField()
    rencana_anggaran = models.IntegerField()    
    dana_akademik = models.IntegerField(default=0)
    dana_tambahan = models.IntegerField(default=0)
    real_dana_akademik = models.IntegerField(null=True)
    real_dana_tambahan = models.IntegerField(null=True)

    deskripsi = models.TextField(default='')
    maksud_tujuan = models.TextField(default='')
    latar_belakang = models.TextField(default='')
    dasar = models.TextField(default='')
    penutup = models.TextField(default='')

    hasil = models.TextField(default='')
    
    kepengurusan = models.ForeignKey(Kepengurusan, on_delete=models.CASCADE)
    ormawa = models.ForeignKey(Ormawa, on_delete=models.CASCADE)
    periode = models.ForeignKey(Periode, on_delete=models.CASCADE)
    jenis = models.ForeignKey(JenisKegiatan, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=StatusKegiatan.choices)

    class Meta:
        verbose_name_plural = "Kegiatan"

    def __str__(self):
        return self.nama

masterData/views/OrmawaView.py
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required
from django.contrib import messages

from BIMA.utils import form_error_redirect, form_success_redirect
from masterData.forms import OrmawaForm, PeriodeForm
from masterData.models import Level, Ormawa
from ormawa.forms import KepengurusanForm
from ormawa.models import Kepengurusan


class OrmawaView:
    @permission_required('ormawa.view_ormawa')
    def index(request):
        ormawaForm = OrmawaForm()
        ormawa = Ormawa.objects.all()

        level = Level.objects.all()

        context = {
            "ormawa": ormawa,
            "level": level,
            "form": ormawaForm,
        }
        return render(request, 'ormawa/index.html', context)
    
    @permission_required('ormawa.view_ormawa')
    def show(request, ormawaID):
        ormawa = Ormawa.objects.filter(id=ormawaID).first()
        kepengurusan = Kepengurusan.objects.filter(ormawa_id=ormawaID).order_by('-periode__tgl_selesai')

        periodeForm = PeriodeForm()
        kepengurusanForm = KepengurusanForm()

        context = {
            "ormawa": ormawa,
            "kepengurusan": kepengurusan,
            "periodeForm": periodeForm,
            "kepengurusanForm": kepengurusanForm,
        }

        return render(request, 'user/ormawa/show.html', context)
    
    @permission_required('ormawa.view_ormawa')
    def search(request):
        if request.method == "POST":
            body = json.loads(request.body)
            ormawa = Ormawa.objects.filter(nama__icontains=body['query'])

            data = []
            for o in ormawa:
                data.append({
                    'singkatan': o.singkatan,
                    'nama': o.nama,
                })
            return JsonResponse(data, safe=False)

    @permission_required('ormawa.add_ormawa')
    def create(request):
        if request.method == "POST":
            form = OrmawaForm(request.POST)
            if form.is_valid():
                ormawa = form.save(commit=False)
                ormawa.save()
                
                return form_success_redirect(request, message="Success Created Ormawa", route='ormawa.index')
            else:
                return form_error_redirect(request, form=form, route='ormawa.index')
    

    @permission_required('ormawa.change_ormawa')
    def edit(request, ormawaID):
        ormawa = Ormawa.objects.filter(id=ormawaID).first()

        if request.method == "POST":
            form = OrmawaForm(request.POST, instance=ormawa)
            if form.is_valid():
                ormawa = form.save(commit=False)
                ormawa.save()

                return form_success_redirect(request, message="Success Modified Ormawa", route='ormawa.index')
            else:
                return form_error_redirect(request, form=form, route='ormawa.index')
            

    @permission_required('ormawa.delete_ormawa')
    def delete(request, ormawaID):
        Ormawa.objects.filter(id=ormawaID).delete()

        return form_success_redirect(request, message="Success Deleted Ormawa", route='ormawa.index')

ormawa/views/KepengurusanView.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth.decorators import permission_required

from BIMA.utils import form_error_redirect, form_success_redirect, is_admin_ormawa, is_admin_kemahasiswaan

from ormawa.forms import *
from ormawa.models import Ormawa, Kepengurusan, Periode
from mahasiswa.models import Mahasiswa


class KepengurusanView:
        
    def index(request):

        form = KepengurusanForm()

        if is_admin_kemahasiswaan(request.user):
            kepengurusan = Kepengurusan.objects.all()
        elif is_admin_ormawa(request.user):
            usrKepengurusan = Kepengurusan.objects.filter(Q(ketua__nim=request.user) | Q(sekretaris__nim=request.user)).first()
            kepengurusan = Kepengurusan.objects.filter(ormawa=usrKepengurusan.ormawa)
        else:
            kepengurusan = []

        context = {
            'kepengurusan': kepengurusan,
            'form': form,
        }
        return render(request, 'kepengurusan/index.html', context)

    def show(request, ormawaName, periodeID):
        form = PengurusForm()
        allowModify = True

        if is_admin_kemahasiswaan(request.user):
            kepengurusan = Kepengurusan.objects.get(ormawa__singkatan=ormawaName, periode__id=periodeID)
            pengurus = Pengurus.objects.filter(kepengurusan=kepengurusan)
        elif is_admin_ormawa(request.user):
            usrKepengurusan = Kepengurusan.objects.filter(Q(ketua__nim=request.user) | Q(sekretaris__nim=request.user)).first()
            kepengurusan = Kepengurusan.objects.get(ormawa=usrKepengurusan.ormawa, periode__id=periodeID)
            pengurus = Pengurus.objects.filter(kepengurusan=kepengurusan)
            if usrKepengurusan != kepengurusan:
                allowModify = False
        else:
            kepengurusan = None
            pengurus = []    

        context = {
            "form": form,
            "allowModify": allowModify,
            "pengurus": pengurus,
            "kepengurusan": kepengurusan,
            "isKepengurusan": True,
        }
        return render(request, 'pengurus/index.html', context)


    @permission_required('ormawa.add_kepengurusan')
    def create(request):
        if request.method == "POST":
            form = KepengurusanForm(request.POST)

            if is_admin_kemahasiswaan(request.user):

                if form.is_valid():
                    kepengurusan = form.save(commit=False)
                    kepengurusan.ormawa = Ormawa.objects.get(id=form.cleaned_data['ormawa'])
                    kepengurusan.periode = Periode.objects.get(id=form.cleaned_data['periode'])
                    kepengurusan.ketua = Mahasiswa.objects.get(nim=form.cleaned_data['ketua'])
                    kepengurusan.sekretaris = Mahasiswa.objects.get(nim=form.cleaned_data['sekretaris'])
                    kepengurusan.npp_wr = Dosen.objects.get(npp=form.cleaned_data['npp_wr'])
                    kepengurusan.npp_pembina = Dosen.objects.get(npp=form.cleaned_data['npp_pembina'])
                    kepengurusan.or_koord = Mahasiswa.objects.get(nim=form.cleaned_data['or_koord'])
                    kepengurusan.save()

                    # return redirect('kepengurusan.index')
                    return form_success_redirect(request, message="Success Created Kepengurusan", route='kepengurusan.index')
                else:
                    return form_error_redirect(request, form=form, route='kepengurusan.index')

    @permission_required('ormawa.change_kepengurusan')
    def edit(request, kepengurusanID):
        if request.method == "POST":
            kepengurusanInstance = Kepengurusan.objects.get(id=kepengurusanID)
            form = KepengurusanForm(request.POST, instance=kepengurusanInstance)

            if is_admin_kemahasiswaan(request.user):

                if form.is_valid():
                    kepengurusan = form.save(commit=False)
                    kepengurusan.ormawa = Ormawa.objects.get(id=form.cleaned_data['ormawa'])
                    kepengurusan.periode = Periode.objects.get(id=form.cleaned_data['periode'])
                    kepengurusan.ketua = Mahasiswa.objects.get(nim=form.cleaned_data['ketua'])
                    kepengurusan.sekretaris = Mahasiswa.objects.get(nim=form.cleaned_data['sekretaris'])
                    kepengurusan.npp_wr = Dosen.objects.get(npp=form.cleaned_data['npp_wr'])
                    kepengurusan.npp_pembina = Dosen.objects.get(npp=form.cleaned_data['npp_pembina'])
                    kepengurusan.or_koord = Mahasiswa.objects.get(nim=form.cleaned_data['or_koord'])
                    kepengurusan.save()
                    # return redirect('kepengurusan.index')
                    return form_success_redirect(request, message="Success Modified Kepengurusan", route='kepengurusan.index')
                else:
                    return form_error_redirect(request, form=form, route='kepengurusan.index')

        else:
            data = {
                "id": kepengurusan.id,
                "nama": kepengurusan.nama,
                "ketua": kepengurusan.ketua.id,
                "sekretaris": kepengurusan.sekretaris.id,
                "tgl_mulai": kepengurusan.periode.tgl_mulai,
                "tgl_selesai": kepengurusan.periode.tgl_selesai,
            }
            return JsonResponse(data, safe=False) 
    
    @permission_required('ormawa.delete_kepengurusan')
    def delete(request, kepengurusanID):
        if request.method == "POST":

            if is_admin_kemahasiswaan(request.user):
                kepengurusan = Kepengurusan.objects.filter(id=kepengurusanID).first()
                kepengurusan.delete()
                # return redirect('kepengurusan.index')
                
                return form_success_redirect(request, message="Success Deleted Kepengurusan", route='kepengurusan.index')

ormawa/templates/kepengurusan/show.html
{% extends "dashboard/layout.html" %}
<!---->
{% block content %}
  <!---->
  {% include "dashboard/broadcrumb.html" with title="Kepengurusan {{ ormawa }} ({{ periode }})" %}
  <div x-data="{ 'isModalOpen': false, pengurusEdit: {}, modalTitle: '', formUrl: '', formBtn: '', }"
       class="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
    {% if not kepengurusan %}
      <div class="m-3 flex justify-center">
        <div>
          <button id="modalOpen"
                  x-on:click=" formUrl = '{% url "kepengurusan.create" ormawa periode %}'; formBtn = 'Create'; isModalOpen = true; modalTitle = 'Create Kepengurusan'; ormawaEdit = { nama: '', singkatan: '', deskripsi: '', jenis: '', status: '', }; "
                  class="block text-center text-primary font-bold">Klik disini untuk membuat</button>
          <span class="block text-center">(( \\ Under Construction \\ ))</span>
        </div>
      </div>
    {% else %}
      <div class="px-4 py-6 md:px-6 xl:px-7.5 flex justify-between">
        <div>
          <input type="text"
                 placeholder="Search"
                 class="w-1/4 rounded-lg border-[1.5px] border-stroke bg-transparent px-5 py-2 font-normal text-black outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:border-form-strokedark dark:bg-form-input dark:text-white dark:focus:border-primary" />
          <a href="#"
             class="inline-flex items-center justify-center rounded-md border border-primary px-10 py-2 text-center font-medium text-primary hover:bg-opacity-90 lg:px-8 xl:px-10">
            Filter
          </a>
        </div>
        <div>
          <button id="modalOpen"
                  x-on:click=" formUrl = '{% url "pengurus.create" kepengurusan.id %}'; formBtn = 'Create'; isModalOpen = true; modalTitle = 'Create Pengurus'; ormawaEdit = { nama: '', singkatan: '', deskripsi: '', jenis: '', status: '', }; "
                  class="inline-flex items-center justify-center rounded-md bg-primary px-10 py-2 text-center font-medium text-white hover:bg-opacity-90 lg:px-8 xl:px-10">
            Create
          </button>
        </div>
      </div>
      <div class="grid grid-cols-6 border-t border-stroke px-4 py-4.5 dark:border-strokedark sm:grid-cols-8 md:px-6 2xl:px-7.5">
        <div class="col-span-3 hidden items-center sm:flex">
          <p class="font-medium">Nama</p>
        </div>
        <div class="col-span-3 hidden items-center sm:flex">
          <p class="font-medium">NIM/NPP</p>
        </div>
        <div class="col-span-1 hidden items-center sm:flex">
          <p class="font-medium">Jabatan</p>
        </div>
      </div>
      <!-- ketua -->
      <div class="grid grid-cols-6 border-t border-stroke px-4 py-4.5 dark:border-strokedark sm:grid-cols-8 md:px-6 2xl:px-7.5">
        <div class="col-span-3 flex items-center">
          <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
            <p class="text-sm font-medium text-black dark:text-white">{{ kepengurusan.ketua.nama }}</p>
          </div>
        </div>
        <div class="col-span-3 flex items-center">
          <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
            <p class="text-sm font-medium text-black dark:text-white">{{ kepengurusan.ketua.nim }}</p>
          </div>
        </div>
        <div class="col-span-1 flex items-center">
          <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
            <p class="text-sm font-medium text-black dark:text-white">Ketua</p>
          </div>
        </div>
        <div class="flex gap-5 justify-end">
          <button x-on:click=" formUrl = '{% url "level.edit" 1 %}'; formBtn = 'Save'; isModalOpen = true; modalTitle = 'Edit Jenis Ormawa'; pengurusEdit = { nama: '{{ k.nama }}', }; ">
            <i class="fa-solid fa-pen"></i>
          </button>
        </div>
      </div>
      <!-- Sekretaris -->
      <div class="grid grid-cols-6 border-t border-stroke px-4 py-4.5 dark:border-strokedark sm:grid-cols-8 md:px-6 2xl:px-7.5">
        <div class="col-span-3 flex items-center">
          <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
            <p class="text-sm font-medium text-black dark:text-white">{{ kepengurusan.sekretaris.nama }}</p>
          </div>
        </div>
        <div class="col-span-3 flex items-center">
          <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
            <p class="text-sm font-medium text-black dark:text-white">{{ kepengurusan.sekretaris.nim }}</p>
          </div>
        </div>
        <div class="col-span-1 flex items-center">
          <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
            <p class="text-sm font-medium text-black dark:text-white">Sekretaris</p>
          </div>
        </div>
        <div class="flex gap-5 justify-end">
          <button x-on:click=" formUrl = '{% url "level.edit" 1 %}'; formBtn = 'Save'; isModalOpen = true; modalTitle = 'Edit Jenis Ormawa'; pengurusEdit = { nama: '{{ k.nama }}', }; ">
            <i class="fa-solid fa-pen"></i>
          </button>
        </div>
      </div>
      {% for p in kepengurusan.pengurus_set.all %}
        <div class="grid grid-cols-6 border-t border-stroke px-4 py-4.5 dark:border-strokedark sm:grid-cols-8 md:px-6 2xl:px-7.5">
          <div class="col-span-3 flex items-center">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
              <p class="text-sm font-medium text-black dark:text-white">{{ p.mahasiswa.nama }}</p>
            </div>
          </div>
          <div class="col-span-3 flex items-center">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
              <p class="text-sm font-medium text-black dark:text-white">{{ p.mahasiswa.nim }}</p>
            </div>
          </div>
          <div class="col-span-1 flex items-center">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-center">
              <p class="text-sm font-medium text-black dark:text-white">{{ p.struktur.nama }}</p>
            </div>
          </div>
          <div class="flex gap-5 justify-end">
            <button x-on:click=" formUrl = '{% url "pengurus.edit" p.id %}'; formBtn = 'Save'; isModalOpen = true; modalTitle = 'Edit Pengurus'; pengurusEdit = { idMahasiswa: '{{ p.mahasiswa.id }}', idStruktur: '{{ p.struktur.id }}' }; ">
              <i class="fa-solid fa-pen"></i>
            </button>
            <form action="{% url 'pengurus.delete' p.id %}"
                  method="post"
                  @submit.prevent="if (confirm('Are you sure?')) $el.submit()">
              {% csrf_token %}
              <button type="submit" @click="confirmed = true">
                <i class="fa-solid fa-trash"></i>
              </button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    {% include "partials/basic_modal.html" %}

  </div>
{% endblock content %}